# Form implementation generated from reading ui file 'new.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class NewLeague_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(465, 523)
        Dialog.setAutoFillBackground(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(parent=Dialog)
        self.spinBox.setWrapping(False)
        self.spinBox.setFrame(True)
        self.spinBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spinBox.setReadOnly(False)
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spinBox.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.spinBox.setKeyboardTracking(True)
        self.spinBox.setProperty("showGroupSeparator", True)
        self.spinBox.setMinimum(4)
        self.spinBox.setMaximum(20)
        self.spinBox.setSingleStep(2)
        self.spinBox.setStepType(QtWidgets.QAbstractSpinBox.StepType.DefaultStepType)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox = QtWidgets.QCheckBox(parent=self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(parent=self.groupBox)
        self.comboBox.setEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.label_teamStyle = QtWidgets.QLabel(parent=self.groupBox)
        self.label_teamStyle.setObjectName("label_teamStyle")
        self.gridLayout.addWidget(self.label_teamStyle, 0, 1, 1, 1)
        self.pushCreateTeam = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushCreateTeam.setObjectName("pushCreateTeam")
        self.gridLayout.addWidget(self.pushCreateTeam, 3, 0, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget = QtWidgets.QListWidget(parent=Dialog)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_2.addWidget(self.listWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushAddOthers = QtWidgets.QPushButton(parent=Dialog)
        self.pushAddOthers.setMinimumSize(QtCore.QSize(120, 50))
        self.pushAddOthers.setObjectName("pushAddOthers")
        self.verticalLayout.addWidget(self.pushAddOthers)
        self.pushStartSimulation = QtWidgets.QPushButton(parent=Dialog)
        self.pushStartSimulation.setMinimumSize(QtCore.QSize(120, 50))
        self.pushStartSimulation.setObjectName("pushStartSimulation")
        self.verticalLayout.addWidget(self.pushStartSimulation)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        self.checkBox.toggled['bool'].connect(self.lineEdit.setEnabled) # type: ignore
        self.checkBox.toggled['bool'].connect(self.comboBox.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700; font-style:italic;\">Enter number of teams</span><span style=\" font-size:12pt; font-style:italic;\"/><span style=\" font-size:12pt; font-style:italic; text-decoration: underline;\">(max:20</span><span style=\" font-size:12pt; font-style:italic;\">)</span></p></body></html>"))
        self.checkBox.setText(_translate("Dialog", "Create your  own team"))
        self.comboBox.setItemText(0, _translate("Dialog", "Balanced"))
        self.comboBox.setItemText(1, _translate("Dialog", "Very Defensive"))
        self.comboBox.setItemText(2, _translate("Dialog", "Defensive"))
        self.comboBox.setItemText(3, _translate("Dialog", "Attacking"))
        self.comboBox.setItemText(4, _translate("Dialog", "Very Attacking"))
        self.label_teamStyle.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700;\">Choose Team Style</span></p></body></html>"))
        self.pushCreateTeam.setText(_translate("Dialog", "Create Team"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Input team name"))
        self.pushAddOthers.setText(_translate("Dialog", "Populate League"))
        self.pushStartSimulation.setText(_translate("Dialog", "Start Simulation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
