# Form implementation generated from reading ui file 'tournament.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(805, 600)
        Form.setMinimumSize(QtCore.QSize(640, 480))
        Form.setStyleSheet("QWidget{\n"
"background-color:rgb(211, 255, 222);\n"
"}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.League_table = QtWidgets.QTableWidget(parent=Form)
        self.League_table.setMinimumSize(QtCore.QSize(551, 301))
        self.League_table.setStyleSheet("QTableWidget{\n"
"background-color:rgb(168, 168, 168);\n"
"}")
        self.League_table.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.League_table.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.League_table.setMidLineWidth(1)
        self.League_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.League_table.setAlternatingRowColors(True)
        self.League_table.setObjectName("League_table")
        self.League_table.setColumnCount(6)
        self.League_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 127))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.League_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.League_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.League_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.League_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.League_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        item.setFont(font)
        item.setBackground(QtGui.QColor(0, 255, 127))
        brush = QtGui.QBrush(QtGui.QColor(108, 177, 92))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.League_table.setHorizontalHeaderItem(5, item)
        self.League_table.horizontalHeader().setCascadingSectionResizes(True)
        self.League_table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.League_table, 0, 0, 1, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_tour = QtWidgets.QPushButton(parent=Form)
        self.btn_tour.setMinimumSize(QtCore.QSize(40, 125))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.btn_tour.setFont(font)
        self.btn_tour.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_tour.setStyleSheet("QPushButton {\n"
"    background-color:rgb(85, 170, 127);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(224, 0, 0);\n"
"    border-style: inset;\n"
"}")
        self.btn_tour.setFlat(False)
        self.btn_tour.setObjectName("btn_tour")
        self.verticalLayout_2.addWidget(self.btn_tour)
        self.btn_league = QtWidgets.QPushButton(parent=Form)
        self.btn_league.setMinimumSize(QtCore.QSize(40, 125))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.btn_league.setFont(font)
        self.btn_league.setStyleSheet("QPushButton {\n"
"    background-color:rgb(85, 170, 127);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 5em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(224, 0, 0);\n"
"    border-style: inset;\n"
"}")
        self.btn_league.setFlat(False)
        self.btn_league.setObjectName("btn_league")
        self.verticalLayout_2.addWidget(self.btn_league)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.Match_results = QtWidgets.QTextEdit(parent=Form)
        self.Match_results.setMinimumSize(QtCore.QSize(390, 220))
        self.Match_results.setStyleSheet("QTextEdit{\n"
"background-color:white;\n"
"}")
        self.Match_results.setObjectName("Match_results")
        self.gridLayout.addWidget(self.Match_results, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.League_table.setSortingEnabled(False)
        item = self.League_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Team Name"))
        item = self.League_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Rating"))
        item = self.League_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Games Played"))
        item = self.League_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Goals Scored"))
        item = self.League_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Goals Conceded"))
        item = self.League_table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Points"))
        self.btn_tour.setText(_translate("Form", "Simulate \n"
"Tour"))
        self.btn_league.setText(_translate("Form", "Simulate\n"
" all"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:700;\">Rounds simulated</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:700; text-decoration: underline;\">0 of 34</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
