# Form implementation generated from reading ui file 'hof.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HoF(object):
    def setupUi(self, HoF):
        HoF.setObjectName("HoF")
        HoF.resize(502, 382)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/images/ball.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        HoF.setWindowIcon(icon)
        HoF.setStyleSheet("QDialog{\n"
"background-color:rgb(211, 255, 222);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(HoF)
        self.verticalLayout.setObjectName("verticalLayout")
        self.HallofFame = QtWidgets.QTableWidget(parent=HoF)
        self.HallofFame.setMaximumSize(QtCore.QSize(520, 400))
        self.HallofFame.setStyleSheet("QTableWidget{\n"
"background-color:qlineargradient(x1: 0, y1: 0, x2: 0.5, y2: 0.5,\n"
"                                stop: 0 #FF92BB, stop: 1 white);\n"
"}")
        self.HallofFame.setObjectName("HallofFame")
        self.HallofFame.setColumnCount(7)
        self.HallofFame.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.HallofFame.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.HallofFame.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.HallofFame.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.HallofFame.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.HallofFame.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.HallofFame.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.HallofFame.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.HallofFame.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.HallofFame.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.HallofFame.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.HallofFame.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.HallofFame.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.HallofFame.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.HallofFame.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.HallofFame.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.HallofFame.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.HallofFame.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.HallofFame)

        self.retranslateUi(HoF)
        QtCore.QMetaObject.connectSlotsByName(HoF)

    def retranslateUi(self, HoF):
        _translate = QtCore.QCoreApplication.translate
        HoF.setWindowTitle(_translate("HoF", "Hall of Fame"))
        item = self.HallofFame.verticalHeaderItem(0)
        item.setText(_translate("HoF", "1"))
        item = self.HallofFame.verticalHeaderItem(1)
        item.setText(_translate("HoF", "2"))
        item = self.HallofFame.verticalHeaderItem(2)
        item.setText(_translate("HoF", "3"))
        item = self.HallofFame.verticalHeaderItem(3)
        item.setText(_translate("HoF", "4"))
        item = self.HallofFame.verticalHeaderItem(4)
        item.setText(_translate("HoF", "5"))
        item = self.HallofFame.verticalHeaderItem(5)
        item.setText(_translate("HoF", "6"))
        item = self.HallofFame.verticalHeaderItem(6)
        item.setText(_translate("HoF", "7"))
        item = self.HallofFame.verticalHeaderItem(7)
        item.setText(_translate("HoF", "8"))
        item = self.HallofFame.verticalHeaderItem(8)
        item.setText(_translate("HoF", "9"))
        item = self.HallofFame.verticalHeaderItem(9)
        item.setText(_translate("HoF", "10"))
        item = self.HallofFame.horizontalHeaderItem(0)
        item.setText(_translate("HoF", "Team Name"))
        item = self.HallofFame.horizontalHeaderItem(1)
        item.setText(_translate("HoF", "Rating"))
        item = self.HallofFame.horizontalHeaderItem(2)
        item.setText(_translate("HoF", "Games"))
        item = self.HallofFame.horizontalHeaderItem(3)
        item.setText(_translate("HoF", "Wins"))
        item = self.HallofFame.horizontalHeaderItem(4)
        item.setText(_translate("HoF", "Draws"))
        item = self.HallofFame.horizontalHeaderItem(5)
        item.setText(_translate("HoF", "GD"))
        item = self.HallofFame.horizontalHeaderItem(6)
        item.setText(_translate("HoF", "Points"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HoF = QtWidgets.QDialog()
    ui = Ui_HoF()
    ui.setupUi(HoF)
    HoF.show()
    sys.exit(app.exec())
